services:
  - type: web
    name: simplepos
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
    headers:
      - path: /*
        name: Service-Worker-Allowed
        value: "/"
      - path: /manifest.json
        name: Content-Type
        value: application/manifest+json
      - path: /
        name: Cache-Control
        value: no-cache
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable 